Repository minhkycho18/DictionaryApp, pull requests merged in 2023-11, with the labels that each got.

#61 DA-Mobile-109-Implement-wordlist-detail-feature
  package-lock.json
  src/api/Subcategory.js
  src/components/AppLoader.js
  src/components/Home/WordList/ItemListVocabOfSub/ItemListVocabOfSub.jsx
  src/components/Home/WordList/ItemSubCategory/ItemSubCategory.jsx
  src/components/Home/WordList/ItemVocabOfSub/ItemVocabOfSub.jsx
  src/components/Home/WordList/ItemVocabOfSub/Styles.js
  src/components/Study/index.jsx
  src/components/YourWordList/ItemWordList/ItemWordList.jsx
  src/helper/http.js
  src/screens/YourWordListDetail.jsx
Labels: Mobile

#63 DA-Mobile-122--Change-font-UI-wordlist-detail
  App.js
  src/components/Home/WordList/ItemAddNewWord/ItemAddNewWord.jsx
  src/components/Home/WordList/ItemAddNewWord/Styles.js
  src/components/Home/WordList/ItemListVocabOfSub/ItemListVocabOfSub.jsx
  src/components/Home/WordList/ItemSubCategory/ItemSubCategory.jsx
  src/components/Home/WordList/ItemVocabOfSub/ItemVocabOfSub.jsx
  src/components/Home/WordList/ItemWordList/ItemWordList.jsx
  src/components/Search/SearchResult/SearchResult.jsx
  src/components/Search/SearchResult/Styles.js
  src/components/Study/ItemSub/ItemSub.jsx
  src/components/Study/ItemSub/Styles.js
  src/components/Study/index.jsx
  src/components/YourWordList/AddWordToSub/Default/AddDefault.jsx
  src/components/YourWordList/AddWordToSub/Default/ItemResult/ItemResult.jsx
  src/components/YourWordList/AddWordToSub/Default/ItemResult/Styles.js
  src/components/YourWordList/ItemWordList/ItemWordList.jsx
  src/helper/http.js
  src/screens/YourWordListDetail.jsx
Labels: Mobile

#73 Feat/DA-Mobile-125-Implement-Add-Subcategory-Feature-In-Wordlist-Detail
  src/components/BottomSheet/FormAdd/Styles.jsx
  src/screens/YourWordListDetail.jsx
Labels: Mobile

#80 Feat/DA-Mobile-142-Implement-Edit-Wordlist-Feature
  src/components/BottomSheet/FormEdit/FormEdit.jsx
  src/components/BottomSheet/FormEdit/Styles.js
  src/components/YourWordList/ItemWordList/ItemWordList.jsx
  src/components/YourWordList/ItemWordList/Styles.js
  src/screens/YourWordList.jsx
  src/screens/YourWordListDetail.jsx
Labels: Mobile

#81 DA-Mobile-143 : UI-public-wordlist
  src/components/Home/WordList/WordListPublic/WordListPublic.jsx
  src/components/PublicWordlist/ItemPublicWordlist/ItemPublicWordlist.jsx
  src/components/PublicWordlist/ItemPublicWordlist/Styles.js
  src/components/PublicWordlist/PublicWordlist.jsx
  src/components/YourWordList/ItemWordList/ItemWordList.jsx
  src/navigations/HomeStack.js
  src/navigations/publicWordlistStack.js
Labels: Mobile

#85 Bugfix/DA-Mobile-145-Bug-Wordlist-Interface
  src/components/BottomSheet/FormEdit/FormEdit.jsx
  src/components/Home/WordList/ItemSubCategory/ItemSubCategory.jsx
  src/components/Home/WordList/ItemSubCategory/Styles.js
  src/components/YourWordList/AddWordList/AddWordList.jsx
  src/components/YourWordList/ItemWordList/ItemWordList.jsx
  src/components/YourWordList/ItemWordList/Styles.js
  src/helper/http.js
  src/screens/VocalDetailScreen.jsx
  src/screens/YourWordList.jsx
Labels: bug

#93 DA-Mobile-160--Fix-UI-ios-and-android
  src/components/BottomSheet/FormAdd/FormAdd.jsx
  src/components/BottomSheet/FormEdit/FormEdit.jsx
  src/components/BottomSheet/ItemWordList/ItemWordList.jsx
  src/components/Game/CardReview/ItemCardReview.jsx
  src/components/Home/WordList/ItemWordList/Styles.js
  src/components/Home/WordList/MyWordList/MyWordList.jsx
  src/components/PublicWordlist/ItemPublicWordlist/Styles.js
  src/components/PublicWordlist/PublicWordlist.jsx
  src/components/Search/SearchResult/SearchResult.jsx
  src/components/Search/SearchResult/Styles.js
  src/components/YourWordList/AddWordList/AddWordList.jsx
  src/components/YourWordList/AddWordToSub/Default/ItemResult/ItemResult.jsx
  src/components/YourWordList/AddWordToSub/Default/ItemResult/Styles.js
  src/components/YourWordList/ItemWordList/ItemWordList.jsx
  src/components/YourWordList/ItemWordList/Styles.js
  src/constants/theme.js
  src/navigations/HomeStack.js
  src/screens/ReviewScreen.jsx
  src/screens/VocalDetailScreen.jsx
  src/screens/YourWordList.jsx
  src/screens/YourWordListDetail.jsx
Labels: bug

#95 Feat/DA-Mobile-158-Create-UI-Detail-Screen-Of-Public-Wordlist
  src/components/Home/WordList/ItemListVocabOfSub_PublicWordlist/ItemListVocabOfSub_PublicWordlist.jsx
  src/components/Home/WordList/ItemSubCategoryOfPublicSub/ItemSubCategoryOfPublicSub.jsx
  src/components/Home/WordList/ItemSubCategoryOfPublicSub/Styles.js
  src/components/Home/WordList/ItemVocabOfSub_PublicWordlist/ItemVocabOfSub_PublicWordlist.jsx
  src/components/Home/WordList/ItemVocabOfSub_PublicWordlist/Styles.js
  src/components/PublicWordlist/ItemPublicWordlist/ItemPublicWordlist.jsx
  src/components/PublicWordlist/ItemPublicWordlist/Styles.js
  src/components/PublicWordlist/PublicWordlist.jsx
  src/navigations/HomeStack.js
  src/navigations/publicWordlistStack.js
  src/screens/PublicWordlistDetail.jsx
Labels: Mobile

#101 feat/DA-Mobile-164-FlashCard-Game-Screen
  App.js
  src/components/Game/CardFlashcard/ItemCardFlashcard.jsx
  src/components/Game/CardFlashcard/Styles.js
  src/constants/theme.js
  src/navigations/gameStack.js
  src/screens/FlashcardScreen.jsx
Labels: Mobile

#102 Feat/DA-Mobile-165 : Call api for review screen and spelling game screen
  App.js
  src/api/Game.js
  src/assets/successPNG.png
  src/components/Game/CardFlashcard/ItemCardFlashcard.jsx
  src/components/Game/CardReview/ItemCardReview.jsx
  src/components/Game/CardReview/Styles.js
  src/components/Game/CardSpelling/ItemCardSpelling.jsx
  src/components/Game/CardSpelling/Styles.js
  src/components/Game/FinishGame.jsx
  src/components/Game/FinishReview.jsx
  src/components/Study/ItemSub/ItemSub.jsx
  src/components/Study/index.jsx
  src/navigations/gameStack.js
  src/screens/FlashcardScreen.jsx
  src/screens/PublicWordlistDetail.jsx
  src/screens/ReviewScreen.jsx
  src/screens/SpellingScreen.jsx
Labels: Mobile

#103 DA-Mobile-170--fix-review-screen
  src/assets/mute.png
  src/components/Game/CardFlashcard/ItemCardFlashcard.jsx
  src/components/Game/CardFlashcard/Styles.js
  src/components/Game/CardReview/ItemCardReview.jsx
  src/components/Game/CardReview/Styles.js
  src/components/Game/CardSpelling/ItemCardSpelling.jsx
  src/components/Game/CardSpelling/Styles.js
  src/screens/PublicWordlistDetail.jsx
Labels: bug

#105 DA-Mobile-171--create-ui-leitner-screen
  src/assets/book.png
  src/assets/history.png
  src/components/Leitner/LeitnerItem/LeitnerItem.jsx
  src/components/Leitner/LeitnerItem/Styles.js
  src/navigations/bottomTab.js
  src/screens/Leitner.jsx
Labels: Mobile

#112 feat/DA-Mobile-178-Implement-Quiz-game
  src/components/Game/CardQuiz/ItemCardQuiz.jsx
  src/components/Game/CardQuiz/Styles.js
  src/components/Game/FinishGame.jsx
  src/screens/QuizScreen.jsx
Labels: Mobile

#115 DA-BE-183: Change logic code update default vocabulary
  src/main/java/com/pbl6/dictionaryappbe/controller/ManagerController.java
  src/main/java/com/pbl6/dictionaryappbe/dto/definition/DefinitionShortDetail.java
  src/main/java/com/pbl6/dictionaryappbe/repository/VocabDefRepository.java
  src/main/java/com/pbl6/dictionaryappbe/service/VocabularyService.java
  src/main/java/com/pbl6/dictionaryappbe/service/VocabularyServiceImpl.java
Labels: enhancement

#120 Feat/DA-Mobile-182-Quiz-Result-Screen
  package-lock.json
  package.json
  src/components/Game/FinishQuiz.jsx
  src/components/Game/ItemVocabOfQuizResult/ItemVocabOfQuizResult.jsx
  src/components/Game/ItemVocabOfQuizResult/Styles.js
  src/navigations/gameStack.js
  src/screens/QuizScreen.jsx
Labels: Mobile

#127 Feat/DA-Mobile-189-Implement-Quiz-Result
  src/components/Game/CardQuiz/ItemCardQuiz.jsx
  src/components/Game/FinishQuiz.jsx
  src/components/Game/ItemVocabOfQuizResult/ItemVocabOfQuizResult.jsx
  src/components/Game/ItemVocabOfQuizResult/Styles.js
  src/screens/QuizScreen.jsx
Labels: Mobile
